# Font i mida de lletra
font_family JetBrainsMono
font_size 10

foreground       #E8DFFF
background       #1A0F2B
cursor           #D8A6FF
selection_background #3A1E5C
selection_foreground #FFFFFF

color0  #1A0F2B
color1  #C678FF
color2  #16a085
color3  #D9A6FF
color4  #9F7FFF
color5  #D8A6FF
color6  #1CDC9A 
color7  #E8DFFF

color8  #aaaaff
color9  #D18AFF
color10 #39FF14
color11 #E0C0FF
color12 #9F7FFF
color13 #3F6D4E
color14 #B8A0FF
color15 #FFFFFF
