#===============================================#
#  This file have my split routes for hyprland  #
#===============================================#

# Monitor settings (chose your resolution and refresh rate)
source = ~/.config/hypr/split-conf/monitors.conf

# Programs and enviroment variables
source = ~/.config/hypr/split-conf/variables.conf

# Autostart programs when you log in
source = ~/.config/hypr/split-conf/autostart.conf

# Window style
source = ~/.config/hypr/split-conf/windowLook.conf

# Animations
source = ~/.config/hypr/split-conf/animations.conf

# Master and misc
source = ~/.config/hypr/split-conf/master-misc.conf

# Input (Set your kb lyout)
source = ~/.config/hypr/split-conf/input.conf

# Keybinding of the enviroment
source = ~/.config/hypr/split-conf/keybindings.conf

# Windows and workspaces configuration
source = ~/.config/hypr/split-conf/windowrule.conf
